## Accepting User Input


In [1]:
li=[ [], [], [], [], [], [], [], [], [] ]
for i in range(9):
    inp = [int(x) for x in input().split()]
    li[i] = inp

0 0 0 0 6 0 0 0 0
4 0 8 0 0 0 0 5 0
0 0 5 0 0 0 9 2 7
6 0 0 0 4 3 0 0 5
0 0 0 0 0 0 0 1 8 
9 0 0 0 5 7 0 0 2
0 0 6 0 0 0 3 7 9
1 0 9 0 0 0 0 6 0 
0 0 0 0 7 0 0 0 0


### Available Puzzle

In [2]:
import numpy as np
print(np.matrix(li))

[[0 0 0 0 6 0 0 0 0]
 [4 0 8 0 0 0 0 5 0]
 [0 0 5 0 0 0 9 2 7]
 [6 0 0 0 4 3 0 0 5]
 [0 0 0 0 0 0 0 1 8]
 [9 0 0 0 5 7 0 0 2]
 [0 0 6 0 0 0 3 7 9]
 [1 0 9 0 0 0 0 6 0]
 [0 0 0 0 7 0 0 0 0]]


## Possibility Function

In [3]:
def possible(y,x,n):
    global li
    for i in range(0,9):
        if li[y][i]==n:
            return False
        
    for i in range(0,9):
        if li[i][x]==n:
            return False
        
    x0 = (x//3)*3
    y0 = (y//3)*3
    
    for i in range(0,3):
        for j in range(3):
            if li[y0+i][x0+i]==n:
                return False
    return True

#### Trying out Some possibilities

In [4]:
possible(4,4,3)

True

In [5]:
possible(8,0,1)

False

## Creating the Solver Function

In [6]:
def solve():
    global li
    for y in range(9):
        for x in range(9):
            if li[y][x]==0:
                for i in range(1,10):
                    if possible(y,x,i):
                        li[y][x]=i
                        solve()
                        li[y][x]=0
                return
            
    print(np.matrix(li))
    input("More Solutions : ")

In [ ]:
solve()

[[2 1 7 5 6 8 4 9 3]
 [4 7 8 3 9 2 1 5 6]
 [3 4 5 6 8 1 9 2 7]
 [6 9 2 1 4 3 7 8 5]
 [7 3 4 9 2 6 5 1 8]
 [9 8 1 4 5 7 6 3 2]
 [8 5 6 2 1 4 3 7 9]
 [1 2 9 7 3 5 8 6 4]
 [5 6 3 8 7 9 2 4 1]]
More Solutions : 
[[2 1 7 5 6 8 4 9 3]
 [4 7 8 9 3 2 1 5 6]
 [3 4 5 8 1 6 9 2 7]
 [6 9 1 2 4 3 7 8 5]
 [7 2 3 6 9 4 5 1 8]
 [9 8 4 1 5 7 6 3 2]
 [8 5 6 4 2 1 3 7 9]
 [1 3 9 7 8 5 2 6 4]
 [5 6 2 3 7 9 8 4 1]]
More Solutions : 
[[2 1 7 5 6 9 4 8 3]
 [4 7 8 3 9 2 1 5 6]
 [3 6 5 4 8 1 9 2 7]
 [6 8 2 1 4 3 7 9 5]
 [7 3 4 9 2 5 6 1 8]
 [9 4 1 6 5 7 8 3 2]
 [8 5 6 2 1 4 3 7 9]
 [1 2 9 7 3 8 5 6 4]
 [5 9 3 8 7 6 2 4 1]]
More Solutions : 
[[2 1 7 5 6 9 4 8 3]
 [4 7 8 3 9 2 1 5 6]
 [3 6 5 4 8 1 9 2 7]
 [6 8 2 1 4 3 7 9 5]
 [7 3 4 9 2 6 5 1 8]
 [9 4 1 8 5 7 6 3 2]
 [8 5 6 2 1 4 3 7 9]
 [1 2 9 7 3 5 8 6 4]
 [5 9 3 6 7 8 2 4 1]]
More Solutions : 
[[2 1 7 5 6 9 8 4 3]
 [4 3 8 7 9 2 1 5 6]
 [8 4 5 3 1 6 9 2 7]
 [6 9 2 1 4 3 7 8 5]
 [7 5 3 9 2 4 6 1 8]
 [9 8 1 6 5 7 4 3 2]
 [5 2 6 4 8 1 3 7 9]
 [1 7 9 2 3 8 5 6 4]
